<?php

const NAME_APP       = 'qiitedon';
const DIR_SEP        = DIRECTORY_SEPARATOR;
const INDENT         = '    ';
const NAME_DIR_CURNT = '.';
const NAME_DIR_PARNT = '..';
const REQUIRE_OS     = 'DARWIN'; //Required OS to compare with PHP_OS

const NAME_FILE_CONF = NAME_APP . '.json';
const PATH_DIR_CURNT = NAME_DIR_CURNT . DIR_SEP;
const PATH_DIR_PARNT = NAME_DIR_PARNT . DIR_SEP;

//Text attributes
const ATTRB_OFF = 0; //	All attributes off
const BOLD_ON   = 1; //	Bold on
const UNDERLINE = 4; //	Underscore (on monochrome display adapter only)
const BLINK_ON  = 5; //	Blink on
const REV_VIDEO = 7; //	Reverse video on
const CONCLD_ON = 8; //	Concealed on
 
//Foreground colors
const FONT_BLACK   = 30; //	Black
const FONT_RED     = 31; //	Red
const FONT_GEEN    = 32; //	Green
const FONT_YELLOW  = 33; //	Yellow
const FONT_BLUE    = 34; //	Blue
const FONT_MAGENTA = 35; //	Magenta
const FONT_CYAN    = 36; //	Cyan
const FONT_WHITE   = 37; //	White
 
//Background colors
const BKGD_BLACK   = 40; //	Black
const BKGD_RED     = 41; //	Red
const BKGD_GREEN   = 42; //	Green
const BKGD_YELLOW  = 43; //	Yellow
const BKGD_BLUE    = 44; //	Blue
const BKGD_MAGENTA = 45; //	Magenta
const BKGD_CYAN    = 46; //	Cyan
const BKGD_WHITE   = 47; //	White

